name = "club-social-media-manager"
main = "backend/src/index.ts"
compatibility_date = "2024-01-01"

# TODO: 以下の環境変数を設定してください
# GEMINI_API_KEY: Gemini APIキー
# DISCORD_WEBHOOK_URL: Discord Webhook URL
# AUTH_SECRET: 認証用シークレットキー

[env.production]
name = "club-social-media-manager-prod"

[env.staging]
name = "club-social-media-manager-staging"

# KVバインディングの設定
[[kv_namespaces]]
binding = "CLUB_KV"
id = "YOUR_KV_NAMESPACE_ID"  # TODO: 実際のKV namespace IDに置き換えてください

# FIXME: Workers AIの設定が必要な場合は以下を追加
# [ai]
# binding = "AI"